### PR TITLE
Update events api

### PR DESCRIPTION
**Pull request by aleksandrzhiliaev**

### CODE REVIEW

**Review by vgarvardt — APPROVED** [review]
What about adding coverage and the badge?

**Comment by vgarvardt** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client) [Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client)

**Comment by rafaeljesus** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client) [Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client)

**Review by c4pone — APPROVED** [review]

**Comment by c4pone** [comment]
+1

[Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client) [Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client) [Approved with PullApprove](https://pullapprove.com/hellofresh/crossengage-python-client/pull-request/15/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/crossengage-python-client)

**Pull request merged**
