### PR TITLE
Add crossengage opt-out endpoints

### PR DESCRIPTION
**Pull request by anvth**

### CODE REVIEW

**Comment by akoshochrein** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by brunoliveira8** [comment]
👍 

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by omarch7** [comment]
👍  Open source

Approved with Zappr  Approved with Zappr  Approved with Zappr

**Comment by fernando-fonseca** [comment]
+1

Approved with Zappr  Approved with Zappr

**Pull request merged**
